### ISSUE TITLE
SSIM function - final formula

### ISSUE THREAD

**Issue by VjeraTurk** [paoloinglese/SPUTNIK#2]
I'm wondering if implementation of SSIM function is correct, in file graph_funcs.R
265 `  ssim <- ( (2*mux*muy+C1) * (2*sigxy+C2) ) / ( (mux**2+muy**2+C1) * (sigx+sigy+C2) )`
should there be
`  ssim <- ( (2*mux*muy+C1) * (2*sigxy+C2) ) / ( (mux**2+muy**2+C1) * (sigx**2+sigy**2+C2) )` Instead?

Formula (13) in http://www.cns.nyu.edu/pub/lcv/wang03-preprint.pdf

(Sorry, I accidently pressed ctrl+Enter instead of  Enter and so the issue got posted before I finished the comment)

**Comment by paoloinglese** [comment]
Could you please elaborate?

**Comment by paoloinglese** [comment]
Yes the denominator of the formula contains the variances.
sigx and sigy are the variances (var(x), var(y)), so the **2 is not necessary.

**Comment by VjeraTurk** [comment]
When taken out of context, it seemed false, but now I see sigx and sigy are actually variances. Thank you for your time

**Comment by paoloinglese** [comment]
You're right, probably I'll change their name into var_x var_y in the next update.
