### ISSUE TITLE
Export Function

### ISSUE THREAD

**Issue by avacecil** [paoloinglese/SPUTNIK#4]
Hi,
Is there an export function built in to the SPUTNIK package or does one have to code it themselves? 
Thanks!

**Comment by paoloinglese** [comment]
Hi,
if you refer to the filters, each filtering function returns an object with all information about the filtered peaks and the used measures.

**Comment by avacecil** [comment]
I want to use this package for pre-processing of MSI data, I was wondering if there is a built-in function to get an imzML file back after the filters have been applied or if I have to write the code to get the processed file. Thank you for your help!

**Comment by paoloinglese** [comment]
No, unfortunately, there's no built in way to extract the imzml. I can suggest to use the MALDIquantForeing package to save the imzml file.

**Comment by avacecil** [comment]
Sounds good, thank you!
